#!/bin/sh

# These are global variables that should be available everywhere

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

export LESSHISTFILE=/dev/null # avoid .lesshist spam in ~

# MOVE SHIT OUT OF THE HOME DIRECTORY AND INTO .config

export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/.pythonrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# Put path additions here:
export PATH=/home/liam/scripts:$PATH
source $HOME/.cargo/env

export EDITOR=nvim

