#!/bin/sh

# This is setup code that should be run whenever an x server is initialized.
# Sourced by both .xinitrc (startx) and .xprofile (dislpay manager).

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.config/X11/.Xresources
usermodmap=$HOME/.config/X11/.Xmodmap

ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

MONITOR_LEFT=$(xgetres monitorLeft)
MONITOR_RIGHT=$(xgetres monitorRight)
xrandr --output $MONITOR_RIGHT --auto --rotate normal
xrandr --output $MONITOR_LEFT --auto --left-of $MONITOR_RIGHT --rotate right

setxkbmap -option caps:swapescape

