let g:my_shortcuts = {
	\ 'i3': '~/.config/i3/config',
	\ 'xresources': '~/.Xresources',
	\ 'xinitrc': '~/.xinitrc',
	\ 'polybar': '~/.config/polybar/config',
	\ 'rofi': '~/.config/rofi/config.rasi',
	\ 'rofitheme': '~/.config/rofi/theme.rasi',
	\ 'zshrc': '~/.zshrc',
	\ 'zprofile': '~/.zprofile',
	\ 'aliases': '~/.aliases',
	\ 'ranger': '~/.config/ranger/rc.conf',
	\ 'vim': '~/.config/nvim/init.vim',
	\ 'xcolors': '~/.Xcolors',
	\ 'alacritty': '~/.config/alacritty/alacritty.yml',
\ }
